apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeapp-deployment
  labels:
    app: timer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: timer
  template:
    metadata:
      labels:
        app: timer
    spec:
      containers:
      - name: timedisplay
        image: parasdongre/display-app:demo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8686

---

apiVersion: v1
kind: Service
metadata:
  name: timer-service
spec:
  type: NodePort
  selector:
    app: timer
  ports:
    - port: 8686
      targetPort: 8686
      nodePort: 30008
